$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  app.name = 'NSRails-Ruby'
  
  # Add NSRails as a vendor project 
  # This reuses the main Xcode project, but in your apps you should copy it into a vendor folder
  app.vendor_project('../../nsrails', :xcode, :target => 'NSRails', :headers_dir => 'Source')
end