$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'NSRails Ruby'
  
  # Add NSRails as a vendor project
  app.vendor_project('../../nsrails', :xcode, :target => "NSRails", :headers_dir => 'source')
end